name: deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >>.env 
          echo WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} >> .env
          echo JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} >> .env
          echo MANAGER_EMAIL=${{ secrets.MANAGER_EMAIL }} >>.env 
          echo MANAGER_PASSWORD=${{ secrets.MANAGER_PASSWORD }} >> .env
          echo S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} >>.env 
          echo S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} >>.env 
          echo S3_BUCKET=${{ secrets.S3_BUCKET }} >>.env
          echo TEST_ACCESS_TOKEN=${{ secrets.TEST_ACCESS_TOKEN}} >>.env
          cat .env

      - name: build server files
        working-directory: ./
        run: |
          yarn
          yarn run build

      - name: zip file
        run: zip -r peekabook.zip ./dist ./scripts ./appspec.yml ./.env ./package.json ./prisma

      - name: AWS configure credientials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./peekabook.zip s3://peekabook-build/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name peekabook-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name GROUP
          --s3-location bucket=peekabook-build,bundleType=zip,key=deploy/peekabook.zip
