name: deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.17.0]
    
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          cat .env
      
      - name: build server files
        working-directory: ./
        run: |
          yarn
          yarn run build

      - name: zip file
        run: zip -r peekabook.zip ./dist ./scripts ./appspec.yml ./.env ./package.json

      - name: AWS configure credientials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name peekabook
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name peekabook-deploy-group
